services:
  grupos-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grupos-service
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SSL=${DATABASE_SSL}
      - PORT=3001
    volumes:
      - .:/app        # monta el codigo local
      - /app/node_modules # evita conflictos con node_modules local
    restart: unless-stopped
    networks:
      - microservicios-topicos

networks:
  microservicios-topicos:
    external: true
